services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit
    ports:
      - "7880:7880"
      - "7881:7881/udp"
    command:
      - "--dev"
      - "--bind"
      - "0.0.0.0"
    environment:
      - "LIVEKIT_KEYS=devkey: secret"